### ISSUE TITLE
[작성] 일기 작성화면 디자인 반영 및 기능 추가

### ISSUE THREAD

**Issue by wishJinit** [TikitakaDiary/MemoryTrace-Android#26]
## 요약
일기 작성화면 디자인 반영 및 기능 추가

## 작업내용
- [ ] 일기 작성화면 디자인 반영 (스티커는 샘플이미지로 대체)
- [ ] 일기 작성화면 기능 추가

**Comment by DohyunYoun** [comment]
- [ ] 키보드 내리는 액션 추가
- [ ] 이미지 추가 시 적용 안됨
- [ ] 전체스크롤 적용 필요
